aviacommerce/avia-docs

content/docs/addresses-api.md, content/docs/auth-api.md, content/docs/line-items-api.md, content/docs/orders-api.md, content/docs/payments-api.md, content/docs/products-api.md, yarn.lock
**Changes**
* Added `json` request &  response.
* Added docs for payment api.
* Modified parameters tables.
* Updated docs with json response.
=> Updated request response json

content/docs/backend-install.md
=> Add wkhtmltopdf in backend installation page

content/home/marketing/build-to-scale.md, content/home/marketing/no-compromises.md, content/home/marketing/open-source.md, src/components/ButtonLink/ButtonLink.js
Corrected some grammatical mistakes, removed redundant phrases and added some links to other websites like elixir-lang. The "No Compromise" section feels more positive and energizing than before!
The links don't look very good IMHO because of the global style on `<a>`.
I changed the `background-color` of the "Get Started" button, the contrast between blue bg and the AviaCommerce brand color is too low, maybe we should add a text-shadow or change the bg color.
=> Rephrase the home page

content/docs/configurations.md
Documentation for general configuration.
=> doc file added for general configuration

content/docs/addresses-api.md, content/docs/checkouts-api.md, content/docs/nav.yml, content/docs/reviews-and-ratings-api.md, content/docs/shipping-api.md, yarn.lock
**Added docs**
* Reviews and rating API
* Shipping API
* Checkout API
* Updated docs for all integrated API
=> Added Reviews and Shipping docs

content/docs/orders.md, content/docs/products.md
Rectified the grammatical errors in Orders and Products module.
=> fixing grammatical errors

content/demo/demo.md, content/demo/nav.yml, content/docs/backend-install.md, content/docs/getting-started.md, content/docs/orders.md, content/docs/payments.md, content/docs/shipments.md, gatsby/createPages.js, src/components/LayoutHeader/Header.js, src/layouts/index.js, src/templates/demo.js, src/utils/createLink.js, src/utils/sectionList.js
Changes
- Adds docs for shipments and payments on the order
detail page.
- Made changes for adding Demo page.
=> Shipments Docs and Demo Page

content/docs/shipments.md
Changes
Add Details for the Package Item Section.
=> Update details for Shipment Docs

content/docs/shipments.md
=> Fix Shipment docs

content/community/support.md, content/demo/demo.md, content/docs/shipments.md
=> Gitter Chat link fix

content/community/support.md, content/docs/products.md, src/components/LayoutHeader/Header.js
Changes
- Minor product page fixes.
- Fix for the demo link.
=> Product Page Fixes

content/demo/nav.yml
Removed redundant navigation links.
=> Demo page Fix

content/docs/addresses-api.md, content/docs/orders-api.md
* Added docs for `update` and `delete` address api.
* Added docs for order list api.
* Docs has been updated for address & order api.
=> Updated docs for order and address api

content/demo/demo.md
=> modify admin credentials

content/demo/demo.md
=> update demo information

content/docs/backend-install.md, content/docs/frontend-install.md
=> AVIA Docs: backend install & frontend install

content/docs/common-errors.md, content/docs/nav.yml, src/prism-styles.js, src/theme.js
=> Added Common Errors Section

src/components/ButtonLink/ButtonLink.js, src/components/LayoutFooter/Footer.js, src/pages/index.js, src/prism-styles.js, src/theme.js
=> Landing page UI modifications

src/pages/404.js, src/templates/community.js, src/templates/demo.js, src/templates/docs.js, src/templates/tutorial.js
=> postfix changes

src/pages/index.js
=> Rename button on home page

content/docs/backend-install.md
Mentioned the mix task to be used to create sample data in the backend installation section.
=> mix task for demo data

content/home/marketing/build-to-scale.md, content/home/marketing/no-compromises.md, content/home/marketing/open-source.md, src/components/LayoutHeader/Header.js, src/pages/index.js
=> Modifications in marketing section at landing page

content/docs/backend-install.md, content/docs/frontend-install.md
Adds instructions for submodule installation instructions.
=> Submodule instructions

content/docs/backend-install.md
=> Fixed minor typo

content/docs/adjustments.md, content/docs/nav.yml, content/docs/payments.md, content/docs/promotions.md, content/docs/shipments.md
Added documentation for the promotions feature. Covers
all the main featurs for promotions.
=> Add Promotion Docs

README.md, content/docs/configurations.md, content/docs/inventory.md, content/docs/nav.yml, content/docs/orders.md, content/docs/payments.md, content/docs/products.md, content/docs/shipments.md, content/docs/users.md
Add docs for Inventory management
=> Inventory docs
